const fs = require('fs');
const path = require('path');
const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const multer = require('multer');
const s3Config = require('../config/s3');
const logger = require('../config/logger');

class MediaStorageService {
  constructor() {
    this.provider = s3Config.provider;
    this.uploadDir = s3Config.uploadDir;

    // Initialize AWS S3 client if configured
    if (this.provider === 's3') {
      this.s3Client = new S3Client({
        region: s3Config.region,
        credentials: {
          accessKeyId: s3Config.credentials.accessKeyId,
          secretAccessKey: s3Config.credentials.secretAccessKey
        }
      });
      logger.info('AWS S3 Storage Provider Initialized');
    } else {
      // Local storage
      const absoluteUploadDir = path.resolve(this.uploadDir);
      if (!fs.existsSync(absoluteUploadDir)) {
        fs.mkdirSync(absoluteUploadDir, { recursive: true });
      }
      logger.info(`Local Storage Provider Initialized (Directory: ${absoluteUploadDir})`);
    }
  }

  getMulterMiddleware() {
    const fileFilter = (req, file, cb) => {
      const allowedTypes = ['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime'];
      if (allowedTypes.includes(file.mimetype)) {
        cb(null, true);
      } else {
        cb(new Error('Invalid file type. Only JPEG, PNG, WEBP and MP4/MOV videos are allowed.'), false);
      }
    };

    if (this.provider === 's3') {
      // Memory storage for S3 uploads
      return multer({
        storage: multer.memoryStorage(),
        fileFilter,
        limits: { fileSize: 100 * 1024 * 1024 } // 100MB max
      });
    } else {
      // Disk storage for local uploads
      const storage = multer.diskStorage({
        destination: (req, file, cb) => {
          cb(null, this.uploadDir);
        },
        filename: (req, file, cb) => {
          const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
          cb(null, file.fieldname + '-' + uniqueSuffix + path.extname(file.originalname));
        }
      });

      return multer({
        storage,
        fileFilter,
        limits: { fileSize: 100 * 1024 * 1024 } // 100MB max
      });
    }
  }

  async uploadFile(file) {
    if (this.provider === 's3') {
      const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9);
      const fileKey = `assets/${uniqueSuffix}-${file.originalname}`;
      
      const uploadParams = {
        Bucket: s3Config.bucket,
        Key: fileKey,
        Body: file.buffer,
        ContentType: file.mimetype
      };

      try {
        await this.s3Client.send(new PutObjectCommand(uploadParams));
        const fileUrl = `https://${s3Config.bucket}.s3.${s3Config.region}.amazonaws.com/${fileKey}`;
        return {
          fileUrl,
          fileName: file.originalname,
          fileType: file.mimetype,
          thumbnailUrl: fileUrl // Fallback thumbnail URL
        };
      } catch (err) {
        logger.error('S3 upload file failed: %o', err);
        throw new Error('Failed to upload file to S3');
      }
    } else {
      // Local file path generated by multer diskStorage
      const fileUrl = `/uploads/${file.filename}`;
      return {
        fileUrl,
        fileName: file.originalname,
        fileType: file.mimetype,
        thumbnailUrl: fileUrl // Local static path
      };
    }
  }

  // Returns video duration estimation (mocked or static for now since it requires complex external binaries like ffprobe)
  getVideoDuration(file) {
    if (file.mimetype.startsWith('video/')) {
      return 15; // default 15s mock duration
    }
    return null;
  }

  async deleteFile(filePathOrUrl) {
    if (!filePathOrUrl) return;
    if (this.provider === 's3') {
      const { DeleteObjectCommand } = require('@aws-sdk/client-s3');
      const keyPrefix = `https://${s3Config.bucket}.s3.${s3Config.region}.amazonaws.com/`;
      if (filePathOrUrl.startsWith(keyPrefix)) {
        const fileKey = filePathOrUrl.substring(keyPrefix.length);
        try {
          await this.s3Client.send(new DeleteObjectCommand({
            Bucket: s3Config.bucket,
            Key: fileKey
          }));
          logger.info(`Successfully deleted file from S3: ${fileKey}`);
        } catch (err) {
          logger.error(`Failed to delete file from S3: ${fileKey}. Error: %o`, err);
        }
      }
    } else {
      let relativePath = filePathOrUrl;
      if (filePathOrUrl.startsWith('/uploads/')) {
        relativePath = filePathOrUrl.substring('/uploads/'.length);
      }
      const absolutePath = path.join(path.resolve(this.uploadDir), relativePath);
      try {
        if (fs.existsSync(absolutePath)) {
          fs.unlinkSync(absolutePath);
          logger.info(`Successfully deleted local file: ${absolutePath}`);
        } else {
          logger.warn(`Local file to delete not found: ${absolutePath}`);
        }
      } catch (err) {
        logger.error(`Failed to delete local file: ${absolutePath}. Error: %o`, err);
      }
    }
  }
}

module.exports = new MediaStorageService();
